### ISSUE TITLE
ZOO-Project is listed in 2 GitHub organizations

### ISSUE THREAD

**Issue by jmckenna** [ZOO-Project/migration#1]
- https://github.com/OSGeo/zoo-project & https://github.com/ZOO-Project
 - source code and all subprojects under the ZOO-Project umbrella should live in the same Github org

**Comment by gfenoy** [comment]
I think that all the ZOO-Project related work should be hosted only in ZOO-Project.

Nevertheless, as the only source code available for the ZOO-Project on GitHub is the one there https://github.com/OSGeo/zoo-project I guess we should keep it alive at least until we complete the SVN source code migration.

**Comment by gfenoy** [comment]
I noted that some project like GRASS use the https://github.com/OSGeo organization as mentioned [there](https://github.com/) (a good reference of GitMigration from the GRASS project).

**Comment by kalxas** [comment]
I have been running the SVN mirror for some years now.
Mirror is done with:
`git svn rebase`
`git push github master`

**Comment by kalxas** [comment]
Once there is a new git repo, I can replace

**Comment by kalxas** [comment]
please let me know if you want me to delete the old git mirror (and perhaps replace it with a mirror to the new git repo)

**Comment by jmckenna** [comment]
I think that would be good @kalxas, as this morning I noticed that Google does not find this repository yet.  So, the sooner we choose and use one repository, the sooner the Google search bots start archiving our chosen repository.  Regarding a new mirror to the new repository: gut reaction: yikes.  I was thinking the goal is to remove all mirrors and use one repository from now one, at least, that was the goal of this ticket.

Feedback from all welcomed/required.

**Comment by kalxas** [comment]
done
