### ISSUE TITLE
Migrate Trac tickets to GitHub issues

### ISSUE THREAD

**Issue by jmckenna** [ZOO-Project/migration#3]
- must include all open and closed Trac tickets
- important step: Trac tickets should remain visible but read-only (at least for a little while, as we adjust to new home)

**Comment by jmckenna** [comment]
- the GRASS team's trac2github script looks very useful: https://github.com/landam/trac2github/tree/grass

**Comment by gfenoy** [comment]
I am in favor of closing this ticket and ticket cleanup.

**Comment by omshinde** [comment]
+1 for closing this ticket and cleanup.

**Comment by gfenoy** [comment]
+1 for closing the ticket and cleanup
